server:
  port: 8088
spring:
  datasource:
    name: test
    password: zhangyu110
    username: root
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    #redis配置
    redis:
      #  数据库索引
      database: 0
      #    服务器地址
      host: 127.0.0.1
      #    服务器连接端口
      port: 6379
      #    链接密码
      password:
      #    链接池
      pool:
        #    最大连接数（负值表示没有限制）
        max-active: 8
        #      最大阻塞等待时间（负值表示没有限制）
        max-wait: 1
        #      最大空闲链接
        max-idle: 8
        #      最小空闲链接
        min-idle: 0
      #    链接超时时间（毫秒）
      timeout: 0
  rabbitmq:
    host: 192.168.188.102
    port: 5672
    username: guest
    password: guest

    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  mapper-locations: classpath*:mapper/*.xml,classpath*:mapper/**/*Mapper.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: com.zhangyu.practice.firstspringboot.com.dao.mapper  # 注意：对应实体类的路径

#pagehelper分页插件
#pagehelper:
#  helperDialect: mysql
#  reasonable: true
#  supportMethodsArguments: true
#  params: count=countSql

dubbo:
  application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
    name: robot-consumer
  registry:                 #注册中心配置，用于配置连接注册中心相关信息。
    address: zookeeper://192.168.188.102:2181
  protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo
    port: 20888